#!/usr/bin/env python3

import glob
import itertools
import os

def count_month(file):
    for id,rows in itertools.groupby(file, lambda l: l[:11]):
        count = [0] * 12
        for row in rows:
            if row[11:15] < "1880":
                continue
            for m in range(12):
                if row[19+m*8:24+m*8] != "-9999":
                    count[m] += 1
        print(id, " ".join(str(c) for c in count))

def main():
    pattern = os.path.expanduser("~/zontem/input/ghcnm*/*.dat")
    filename = glob.glob(pattern)[-1]
    count_month(open(filename))


if __name__ == '__main__':
    main()
